name: Partial Sync Notion Star

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  partial-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - uses: actions/checkout@v2

      - name: Download cache storage of last build
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: partial-sync.yml
          workflow_conclusion: success
          name: notion-sync-storage
          path: .cache

      - name: Setup environment
        uses: actions/setup-node@v2.2.0
        with:
          always-auth: false
          node-version: 16.x
          cache: yarn

      - run: yarn

      - name: Run Partial Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 5000
          PARTIALSYNC_LIMIT: 20
          REPO_TOPICS_LIMIT: 100
        run: npm start

      - uses: actions/upload-artifact@v2
        with:
          name: notion-sync-storage
          path: .cache
